# -*- coding: utf-8 -*-
"""MeetingGenerator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UVRcZW9iJ0jIfbbCjc2VF3SBlviTzgF
"""

#==========================
#MEETING MINUTES GENERATOR
#==========================

import pandas as pd
from datetime import datetime
print("MEETING MINUTE GENERATOR\n")

#user input
meeting_title=input("Enter meeting title:")
date=input("Enter meeting date(dd-mm-yyyy):")
time=input("Enter  meeting time: ")
participants=input("Enter participants(comma separated):")
agenda=input("Enter agenda points (common separate):")
decisions=input("Enter decisions taken(comma separate):")
action_items=input("Enter action items(comma separate):")
prepared_by=input("prepared_by:")

#process inputs
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",") if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",") if d.strip()]
actions_list=[a.strip() for a in action_items.split(",") if a.strip()]

# Create structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda": ", ".join(agenda_list),
    "Decisions Taken": ", ".join(decisions_list),
    "Action Items": ", ".join(actions_list),
    "Prepared_by":prepared_by,
    "Generated_On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

# Convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting Minutes Generated Successfully\n")
display(df)

# Save as CSV
df.to_csv("meeting_minutes.csv", index=False)
print("\n File saved as meeting_minutes.csv")