# -*- coding: utf-8 -*-
"""Product review Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180NpSYd3XpNRGPNJ-4KnKv3qHJkrj-QM
"""

!pip install transformers torch
from transformers import pipeline
import pandas as pd

#Load sentiment analysis model
sentiment=pipeline("sentiment-analysis")

#sample
reviews="""the laptop starts quickly and works smoothly for dialy tasks.
the screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
the fan makes noise when many apps are running.
overall,it is a good laptop for students but not for gaming.
"""

# Split review into sentences
sentences = reviews.split(",")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)

    elif result["label"] == "NEGATIVE":
        cons.append(s)

# Take only first 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

# Create DataFrame
df = pd.DataFrame({
    "Pros": pd.Series(pros),
    "Cons": pd.Series(cons)
})

print(df)

