# -*- coding: utf-8 -*-
"""Text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0RJrBDyIu5xi2Rffofs_xh6P7h3WM_a
"""

!pip install transformers torch

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "Artificial Intelligence in finance will"

result = generator(
    prompt,
    max_length=50,
    num_return_sequences=1
)

print("AI Generated text:")
print(result[0]['generated_text'])