# -*- coding: utf-8 -*-
"""TIMETABLE GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iik2ESIZQKjlzoYXJqQYw-0CQmE7uOs5
"""

import pandas as pd
import random

print("TIMETABLE GENERATION\n")
#user inputs
subjects_input=input("Enter subjects(comma seperate):")
days_input=input("Enter days (comma separate):")
periods_per_day=int(input("Enter number of periods per day:"))

#process input
subjects=[s.strip() for s in subjects_input.split(",") if s.strip()]
days=[d.strip() for d in days_input.split(",") if d.strip()]

#validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day<=0:
  print("invalid input.please try again.")
else:
  timetable={}

  for day in days:
    timetable[day]=random.choices(subjects,k=periods_per_day)

#create dataframe
df=pd.DataFrame(timetable)
df.index=[f"periods{i+1}" for i in range(periods_per_day)]
print("\nTimetable generated successfully\n")
display(df)

#save timetable
df.to_csv("timetable.csv")
print("\nTimetable saved as timetable.csv")